### ISSUE TITLE
Hue immersive won't connect to bridge 2.0

### ISSUE THREAD

**Issue by SCZattix** [Blodjer/HueImmersive#14]
Hello,

First of all before i push the bridge button i have this on the launcher/program:
 http://prntscr.com/a9ip5q
(it's normal i think)

 But then, when i push on the button of the bridge i have this:
http://prntscr.com/a9ipe1
'it's not normally because it bugs or whatever :s)

Hope you guys can help me,
thanks!

**Comment by polykoma** [comment]
Hey man i changed to bridge 2.0 for month now and everything works like with 1.0 

Must be a problem on your side.
Sorry to say

**Comment by bandedos** [comment]
I have the same problem. Other applications works OK.
