### ISSUE TITLE
Request: Adjust Auto Turn Off Lights Sensitivity

### ISSUE THREAD

**Issue by siliconkibou** [Blodjer/HueImmersive#7]
It would be wonderful if we could adjust the range or sensitivity of the Auto Turn Off Lights.  I find that sometimes the screen content is not dark enough to justify the light turning completely off, and it'd be nice to have a mechanism to adjust that threshold.

Keep up the great work!

**Comment by polykoma** [comment]
+1 here.

would be a lovely feature!

**Comment by Blodjer** [comment]
Hi and sorry for the late answer,
before i stopped developing HueImmersive (1 year ago) i got a request for this feature. So I implemented it in a development version.
You can download it if you want but keep in mind that this is just an unfinished development build: [HueImmersiveDev.zip](https://github.com/Blodjer/HueImmersive/files/84102/HueImmersiveDev.zip)

Regards,
Jannik

**Comment by polykoma** [comment]
I will try and give feedback as soon as Im home again!

You are the best. Thank you

Theres is some question from me to you left in the "long discussion" problem thread.
Can you check?
